columns:
  step: int
  type: object
  amount: float
  nameOrig: object
  oldbalanceOrg: float
  newbalanceOrig: float
  nameDest: object
  oldbalanceDest: float
  newbalanceDest: float
  isFraud: int
  isFlaggedFraud: int

target_column:
  name: isFraud